name: daily-rebased-chart-job-execution

on:
  schedule:
    - cron: '50 8 * * *' # UTC time
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set script permissions
        run: chmod +x ./t/iota-rebased-charts/job.sh

      - name: Job execution
        run: bash ./t/iota-rebased-charts/job.sh

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "patricklangx"
          git add t/iota-rebased-charts/data.csv
          git commit -m "Daily data.csv update."

      - name: Push changes
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
