name: daily-rebased-chart-job-execution

on:
  schedule:
    - cron: '50 8 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run bash script
        run: |
          bash ./t/iota-rebased-charts/job.sh

          git config --global user.name "patricklangx"
          git config --global user.email "actions@github.com"
          
          timestamp=$(date +'%Y%m%d%H%M%S')
          branch_name="update-csv-$timestamp"

          git checkout -b "$branch_name"

          git add t/iota-rebased-charts/data.csv

          git commit -m "Daily file update"

          git push origin "$branch_name"

          git checkout main
          git merge --no-ff "$branch_name"
          git push origin main

          # delete the temporary branch
          git branch -d "$branch_name"
          git push origin --delete "$branch_name"
